# This file tells Netlify how to build your site.

[build]
  command = "npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10.9.3"
  
[build.processing]
  skip_install = true

# --- EDGE FUNCTIONS ---

# 1. Short Username Links
[[edge_functions]]
  function = "bot-proxy"
  path = "/@*"

# Long Shop Links (for the Redirect)
[[edge_functions]]
  function = "bot-proxy"
  path = "/shop/*"

# 2. Blog
[[edge_functions]]
  function = "bot-proxy"
  path = "/blog/*"

# 3. All Deep Links
[[edge_functions]]
  function = "bot-proxy"
  path = "/deeplink/*"

# --- ROUTING & HEADERS ---

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"